name: ci 
on:
  push:
    branches:
      - main 
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:  # mkdocs-blogging-plugin 给出的渲染问题解决方案
          fetch-depth: 0
      - uses: actions/setup-python@v3
        with:
          python-version: 3.x
      - run: pip install mkdocs==1.1.2
      - run: pip install mkdocs-material
      - run: pip install mkdocs-blogging-plugin  # 记得安装其他依赖的库
      - run: mkdocs gh-deploy
    env:
        EXTRA_PACKAGES: git-lfs