name: ci 
on:
  push:
    branches:
      - main 
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:  # mkdocs-blogging-plugin 给出的渲染问题解决方案
          fetch-depth: 0
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: | 
          python -m pip install --upgrade pip
          pip install mkdocs
          pip install mkdocs-material
          pip install mkdocs-blogging-plugin  # 记得安装其他依赖的库
          mkdocs gh-deploy
    env:
        CONFIG_FILE: mkdocs.yml
        EXTRA_PACKAGES: git-lfs